version: '3.8'

services:
  app:
    image: yprog:latest
    build: .
    ports:
      - "8085:8085"
    volumes:
      - /etc/ssl:/etc/ssl:ro
    command:
      [
        "/yprog/yprog",
        "-tls=true",
        "-cert=/etc/ssl/cert_vchub_net.pem",
        "-key=/etc/ssl/key_vchub_net.pem"
      ]
