version: '2'

services:
  app:
    image: yprog:latest
    build: .
    ports:
      - "8085:8085"
    volumes:
      - /etc/ssl:/etc/ssl:ro
    command:
      [
        "-tls=true",
        "-cert=/etc/ssl/cert.pem",
        "-key=/etc/ssl/key.pem"
      ]
